name: Build & Deploy
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup PNPM 📦
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Deps & Build 🛠️
        run: |
          pnpm i
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
